### ISSUE TITLE
BETA TEST

### ISSUE THREAD

**Issue by BigMikeM** [var-and-peace/BookSnaps#33]
- [x] Have manual input page ready to test (issue #7)
  - [x] Should be able to add to database (#34)
  - [x] Can check with API to fill in missing data
- [x] Touch up UI/UX
- [x] Database is able to store info received from XML(#34)
